// <auto-generated />
namespace FullStackApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adding_department : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_department));
        
        string IMigrationMetadata.Id
        {
            get { return "201802271651181_adding_department"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
